name: Update WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wakatime Readme
        uses: anmol0998/wakatime-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
