name: WakaTime Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          theme: synthwave
          config_timezone: America/Sao_Paulo
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, languages-graphs, editors
